name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    name: Main pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r python/requirements.txt
      - uses: psf/black@stable
      - name: 'clang-format'
        run: |
          find src include -name '*.cpp' -o -name '*.h' -o -name '*.hpp' | xargs clang-format --Werror -n
      - name: 'Install FFmpeg'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libavcodec-dev libavdevice-dev libavformat-dev libswscale-dev
          version: 1.0
      - name: wheel
        run: |
          pip install build
          python -m build . --wheel